<a href="https://colab.research.google.com/github/Prathamesh-Shanbhag/MLDLS2021/blob/main/Classification_of_Stars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 #  ***Importing Libraries & Working on Data***

In [1]:
# Importing the Required Libraries Numpy & Pandas.
import numpy as np
import pandas as pd

In [2]:
# Reading from CSV Dataset file.
dataset = pd.read_csv('Stars.csv')

print(dataset)

     Temperature              L          R    A_M  Color Spectral_Class  Type
0           3068       0.002400     0.1700  16.12    Red              M     0
1           3042       0.000500     0.1542  16.60    Red              M     0
2           2600       0.000300     0.1020  18.70    Red              M     0
3           2800       0.000200     0.1600  16.65    Red              M     0
4           1939       0.000138     0.1030  20.06    Red              M     0
..           ...            ...        ...    ...    ...            ...   ...
235        38940  374830.000000  1356.0000  -9.93   Blue              O     5
236        30839  834042.000000  1194.0000 -10.63   Blue              O     5
237         8829  537493.000000  1423.0000 -10.73  White              A     5
238         9235  404940.000000  1112.0000 -11.23  White              A     5
239        37882  294903.000000  1783.0000  -7.80   Blue              O     5

[240 rows x 7 columns]


**TARGET: Type**


Legend Key for Star Type
from 0 to 5

*Red Dwarf - 0,*

*Brown Dwarf - 1,*

*White Dwarf - 2,*

*Main Sequence - 3,*

*Super Giants - 4,*

*Hyper Giants - 5.* 

In [4]:
dataset['Type'] = dataset['Type'].astype('category')
# Encoding Not Required since Dataset has in-built codes for categories.

In [14]:
# X has all rows & columns except type column, Y has all rows and target attribute which is Type.
X = dataset.iloc[:,0:4].values
Y = dataset.iloc[:,-1].values

In [15]:
print(X.shape, Y.shape)

(240, 4) (240,)


In [19]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)
print(X_train.shape, X_test.shape)

(168, 4) (72, 4)


 #  ***Logistic Regression***








In [20]:
from sklearn.linear_model import LogisticRegression

modellr = LogisticRegression()
modellr.fit(X_train, Y_train)

Y_pred = modellr.predict(X_test)
print(Y_test, Y_pred)


[1, 1, 2, 1, 0, ..., 1, 0, 5, 2, 1]
Length: 72
Categories (6, int64): [0, 1, 2, 3, 4, 5] [2 2 2 2 2 2 3 2 3 4 2 2 5 4 5 4 5 2 2 2 3 2 5 5 2 2 2 2 2 2 4 5 2 4 2 2 2
 2 2 2 4 2 2 2 5 5 5 2 4 5 2 2 2 4 4 3 4 4 5 2 2 2 2 2 3 5 3 2 2 5 2 2]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


lbfgs stand for: "Limited-memory Broyden–Fletcher–Goldfarb–Shanno Algorithm". It is one of the solvers' algorithms provided by Scikit-Learn Library.

The term limited-memory simply means it stores only a few vectors that represent the gradients approximation implicitly.

It has better convergence on relatively small datasets.

Algorithm convergence:

In simple words. If the error of solving is ranging within very small range (i.e., it is almost not changing), then that means the algorithm reached the solution (not necessary to be the best solution as it might be stuck at what so-called "local Optima").

In [21]:
from sklearn.metrics import  confusion_matrix, accuracy_score, precision_score, recall_score

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Accuracy:", accuracy_score(Y_test, Y_pred)) 
print("Precision:", precision_score(Y_test, Y_pred, average=None))
print("Recall:", recall_score(Y_test, Y_pred, average = None))

Confusion Matrix:
 [[ 0  0 10  0  0  0]
 [ 0  0 16  0  0  0]
 [ 0  0 12  0  0  0]
 [ 0  0  4  5  0  0]
 [ 0  0  0  1 11  0]
 [ 0  0  0  0  0 13]]
Accuracy: 0.5694444444444444
Precision: [0.         0.         0.28571429 0.83333333 1.         1.        ]
Recall: [0.         0.         1.         0.55555556 0.91666667 1.        ]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


There are some labels in Y_test, which dont appear in Y_pred and hence it is ill-defined, & Since these are warnings they can be ignored but we should be able to handle missing data/labels to increase accuracy 

 #  ***K-Nearest Neighbour Classifier***

In [24]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

Y_pred_knn = knn.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_knn))
print("Accuracy:", accuracy_score(Y_test, Y_pred_knn)) 

Confusion Matrix:
 [[ 6  4  0  0  0  0]
 [ 5 11  0  0  0  0]
 [ 0  0 11  1  0  0]
 [ 0  0  2  7  0  0]
 [ 0  0  0  1  6  5]
 [ 0  0  0  1  7  5]]
Accuracy: 0.6388888888888888


 #  ***Decision Tree Classifier***

In [27]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

dtc= DecisionTreeClassifier()
dtc.fit(X_train, Y_train)

Y_pred_dtc = dtc.predict(X_test)

print("Confusion Matrix: \n", confusion_matrix(Y_test, Y_pred_dtc))
print("Accuracy:", accuracy_score(Y_test, Y_pred_dtc)) 

Confusion Matrix: 
 [[10  0  0  0  0  0]
 [ 0 16  0  0  0  0]
 [ 0  0 12  0  0  0]
 [ 0  0  0  9  0  0]
 [ 0  0  0  0 12  0]
 [ 0  0  0  0  0 13]]
Accuracy: 1.0


 #  ***Random Forest***

In [26]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(X_train, Y_train)

Y_pred_rfc = rfc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_rfc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_rfc))

Confusion Matrix:
 [[10  0  0  0  0  0]
 [ 0 16  0  0  0  0]
 [ 0  0 12  0  0  0]
 [ 0  0  0  9  0  0]
 [ 0  0  0  0 12  0]
 [ 0  0  0  0  0 13]]
Accuracy:
 1.0


In [29]:
#Import svm model
from sklearn import svm

clf = svm.SVC(kernel='linear') # Linear Kernel
clf.fit(X_train, Y_train)

Y_pred_clf = clf.predict(X_test)
print("Confusion Matrix \n:", confusion_matrix(Y_test, Y_pred))
print("Accuracy:", accuracy_score(Y_test, Y_pred))
print("Precision:", precision_score(Y_test, Y_pred, average=None))
print("Recall:", recall_score(Y_test, Y_pred, average=None))

Confusion Matrix 
: [[ 0  0 10  0  0  0]
 [ 0  0 16  0  0  0]
 [ 0  0 12  0  0  0]
 [ 0  0  4  5  0  0]
 [ 0  0  0  1 11  0]
 [ 0  0  0  0  0 13]]
Accuracy: 0.5694444444444444
Precision: [0.         0.         0.28571429 0.83333333 1.         1.        ]
Recall: [0.         0.         1.         0.55555556 0.91666667 1.        ]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))




*   Confusion Matrix is 6x6 because there are 6 categories which the data can be classifies into.
*  Precision & Recall need to have Average= None because this is a multi-class classification & not Binary class classification where averaging is required, hence here we set it to None when calculating Precision & Recall.

