<a href="https://colab.research.google.com/github/Prathamesh-Shanbhag/MLDLS2021/blob/main/Multiple_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing the Required Libraries Numpy,Pandas & MatplotLib.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
# Reading from CSV Dataset file.
dataset = pd.read_csv('CO2_data2.csv')

print(dataset)

      Engine Size(L)  ...  CO2 Emissions(g/km)
0                2.0  ...                  196
1                2.4  ...                  221
2                1.5  ...                  136
3                3.5  ...                  255
4                3.5  ...                  244
...              ...  ...                  ...
7380             2.0  ...                  219
7381             2.0  ...                  232
7382             2.0  ...                  240
7383             2.0  ...                  232
7384             2.0  ...                  248

[7385 rows x 4 columns]


In [37]:
# Assigning the values to two variables X & Y using List Slicing (Adding all Columns except Target Attribute to X)
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,-1].values

print(X)
print(Y)

[[ 2.   4.   9.9]
 [ 2.4  4.  11.2]
 [ 1.5  4.   6. ]
 ...
 [ 2.   4.  11.7]
 [ 2.   4.  11.2]
 [ 2.   4.  12.2]]
[196 221 136 ... 240 232 248]


In [62]:
#Splitting the data into Training and Testing Data (Using 0.3 is giving better accuracy by approx ~ 2%)
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3)
print(X_train.shape, X_test.shape)

(5169, 3) (2216, 3)


In [63]:
#Fitting Simple Linear Regression Model using X_train & Y_train values
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [64]:
#Predicting the test results
Y_pred = model.predict(X_test)
print(Y_pred)
print(Y_train)

[224.54773899 268.05725461 318.28853982 ... 213.46248817 199.63870242
 203.13810592]
[274 187 221 ... 240 172 138]


In [65]:
#Calculate Accuracy
accuracy = model.score(X_test,Y_test)
print(accuracy)

0.8831088391134028


In [66]:
# Predicting on an external Data
test_data = np.array([[ 2,6,112]])
test_pred = model.predict(test_data)
print(test_pred)

[1347.47858372]


In [68]:
engineSize =int(input("What is your Engine Size? "))
cylinderNumber = int(input("Number of cyclinders your engine has? "))
fuelConsumption = int(input("What is your fuel consumption in L/100km? "))

co2Emission = model.predict(np.array([[engineSize, cylinderNumber, fuelConsumption]])) 
print('Estimated CO2 Emission with ' + str(fuelConsumption) + ' Litres of Fuel , Engine Size =  '+ str(engineSize) + ' & No of Cylinders = ' + str(cylinderNumber) + ' is ' + str(co2Emission[0]) + ' gm per kilometer')

What is your Engine Size? 4
Number of cyclinders your engine has? 8
What is your fuel consumption in L/100km? 350
Estimated CO2 Emission with 350 Litres of Fuel , Engine Size =  4 & No of Cylinders = 8 is 4008.9111314415204 gm per kilometer
